name: CI

on: [push, pull_request]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate Helm Release from Helm Repo
        uses: ./
        with:
          helmRelease: test/flagger.yaml
          kubernetesVersion: 1.16.0
          helmVersion: v2
      - name: Validate Helm Release from Git Repo
        uses: ./
        with:
          helmRelease: test/podinfo.yaml
          helmVersion: v3
      - name: Validate Helm Release without values
        uses: ./
        with:
          helmRelease: test/podinfo.yaml
          ignoreValues: true
  test-dir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate all Helm Releases in the test dir
        uses: ./
        with:
          helmRelease: test/
        # TODO: Check that 3 things got tested?
  push-container:
    runs-on: ubuntu-latest
    needs: [test-action, test-dir]
    steps:
      - uses: actions/checkout@v1
      - name: Publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@2.7
        with:
          name: stefanprodan/hrval
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true
